export default {
  nav_about: "About",
  nav_services: "Services",
  nav_projects: "Projects",
  nav_contact: "Contact",

  hero_badge: "Operating Since 2015",
  hero_title: "High-Quality Steel Construction Solutions",
  hero_description: "Providing steel fabrication and construction services for industrial and commercial projects across Indonesia. Strong structures, high precision, and guaranteed durability.",
  hero_cta_primary: "Free Consultation",
  hero_cta_secondary: "View Projects",

  about_section_label: "About Us",
  about_paragraph1: "Established in 2015, Ksatria Baja Nusantara has grown to become one of the most trusted steel construction companies in Indonesia. Located in Bekasi, West Java, we serve national scale projects with focus on quality, precision, and durability.",
  about_paragraph2: "Every project we undertake is based on solid engineering principles and the highest industry safety standards.",
  stat_years: "Years Experience",
  stat_projects: "Completed Projects",
  stat_safety: "Safety Incidents",

  value_precision_title: "Precision",
  value_precision_desc: "High accuracy in every detail",
  value_integrity_title: "Integrity",
  value_integrity_desc: "Trust is our foundation",
  value_durability_title: "Durability",
  value_durability_desc: "Structures last for decades",

  services_section_label: "Our Services",
  services_title: "Complete Construction Solutions",
  service1_title: "Steel Structure Fabrication",
  service1_desc: "Fabrication of steel beams, columns, and structural components according to project specifications with high precision tolerance.",
  service2_title: "Industrial Building Construction",
  service2_desc: "Construction of warehouses, factories, and industrial facilities with efficient and fast steel construction systems.",
  service3_title: "Renovation & Reinforcement",
  service3_desc: "Repair and reinforcement of existing building structures to increase load capacity and building lifespan.",
  service4_title: "Design & Consultation",
  service4_desc: "Steel structure engineering design services using CAD software and professional load analysis.",

  projects_section_label: "Portfolio",
  projects_title: "Projects We Have Completed",
  project_completed: "Completed",
  project1_title: "Bekasi Logistics Warehouse",
  project1_desc: "Construction of 10,000 m² logistics warehouse with earthquake resistant light steel structure.",
  project1_highlight: "35% capacity increase",
  project2_title: "Karawang Manufacturing Plant",
  project2_desc: "Factory floor structure reinforcement for additional 120 ton production machine load.",
  project2_highlight: "Zero operational downtime",
  project3_title: "Jakarta Commercial Canopy",
  project3_desc: "Design and construction of commercial area parking canopy with modern design and weather resistance.",
  project3_highlight: "25+ year lifespan",

  workflow_section_label: "Work Process",
  workflow_title: "How We Work",
  workflow1_title: "Consultation & Survey",
  workflow1_desc: "Site visit and detailed project requirements analysis.",
  workflow2_title: "Engineering Design",
  workflow2_desc: "Design drawing creation and structural calculation with CAD.",
  workflow3_title: "Fabrication",
  workflow3_desc: "Cutting, welding, and component finishing in workshop.",
  workflow4_title: "Installation",
  workflow4_desc: "On-site structure installation with professional team.",
  workflow5_title: "Quality Check",
  workflow5_desc: "Final inspection and project handover with warranty.",

  advantages_section_label: "Advantages",
  advantages_title: "Why Choose Us",
  adv1_title: "Modern Machinery",
  adv1_desc: "Using CNC fabrication equipment for highest precision.",
  adv2_title: "CAD Design",
  adv2_desc: "Structure planning with professional engineering software.",
  adv3_title: "Experienced Engineers",
  adv3_desc: "Team with certification and over 10 years experience.",
  adv4_title: "Strict Quality Control",
  adv4_desc: "Every component passes 3 inspection stages before installation.",

  testimonials_label: "Client Testimonials",
  testimonials_title: "What Our Clients Say",
  testimonial1_text: "Our warehouse project was completed 2 weeks ahead of schedule. The structure quality is very satisfying and the team is very professional.",
  testimonial1_name: "Budi Santoso",
  testimonial1_position: "Director, Nusantara Logistics",
  testimonial2_text: "Our factory structure reinforcement was done without stopping production. Very professional and understands industrial needs.",
  testimonial2_name: "Siti Rahayu",
  testimonial2_position: "Factory Manager, Multi Manufacturing",
  testimonial3_text: "The canopy design matches our building concept perfectly. Work is neat and on time. Highly recommended.",
  testimonial3_name: "Andi Pratama",
  testimonial3_position: "Owner, Jakarta Commercial Building",

  contact_section_label: "Contact Us",
  contact_title: "Ready To Build Your Project?",
  contact_description: "Consult your steel construction project with our expert team. We will provide the best offer and solution according to your needs.",
  contact_phone_label: "Phone",
  contact_address_label: "Address",
  contact_response_label: "Response Time",
  contact_response_text: "We will contact you within 24 hours",
  contact_cta_whatsapp: "Contact via WhatsApp",
  contact_label_name: "Full Name",
  contact_label_email: "Email",
  contact_label_phone: "Phone Number",
  contact_label_message: "Project Details",
  contact_placeholder_message: "Describe the project you want to build...",
  contact_submit: "Send Consultation Request",

  footer_nav: "Navigation",
  footer_contact: "Contact",
  footer_description: "Professional steel construction company providing fabrication and structure construction solutions for industrial and commercial projects across Indonesia.",
  footer_copyright: "Copyright © 2026 Ksatria Baja Nusantara. All rights reserved."
}
