export default {
  nav_about: "Tentang",
  nav_services: "Layanan",
  nav_projects: "Proyek",
  nav_contact: "Kontak",

  hero_badge: "Beroperasi Sejak 2015",
  hero_title: "Solusi Konstruksi Baja Berkualitas Tinggi",
  hero_description: "Menyediakan layanan fabrikasi dan konstruksi baja untuk proyek industri dan komersial di seluruh Indonesia. Struktur kuat, presisi tinggi, dan ketahanan terjamin.",
  hero_cta_primary: "Konsultasi Gratis",
  hero_cta_secondary: "Lihat Proyek",

  about_section_label: "Tentang Kami",
  about_paragraph1: "Didirikan pada tahun 2015, Ksatria Baja Nusantara telah tumbuh menjadi salah satu perusahaan konstruksi baja terpercaya di Indonesia. Berlokasi di Bekasi, Jawa Barat, kami melayani proyek skala nasional dengan fokus pada kualitas, presisi, dan ketahanan.",
  about_paragraph2: "Setiap proyek yang kami kerjakan didasarkan pada prinsip rekayasa yang solid dan standar keselamatan industri tertinggi.",
  stat_years: "Tahun Pengalaman",
  stat_projects: "Proyek Selesai",
  stat_safety: "Insiden Keselamatan",

  value_precision_title: "Presisi",
  value_precision_desc: "Ketelitian tinggi di setiap detail",
  value_integrity_title: "Integritas",
  value_integrity_desc: "Kepercayaan adalah dasar",
  value_durability_title: "Ketahanan",
  value_durability_desc: "Struktur bertahan puluhan tahun",

  services_section_label: "Layanan Kami",
  services_title: "Solusi Konstruksi Lengkap",
  service1_title: "Fabrikasi Struktur Baja",
  service1_desc: "Fabrikasi balok baja, kolom, dan komponen struktur sesuai spesifikasi proyek dengan toleransi presisi tinggi.",
  service2_title: "Konstruksi Bangunan Industri",
  service2_desc: "Pembangunan gudang, pabrik, dan fasilitas industri dengan sistem konstruksi baja yang efisien dan cepat.",
  service3_title: "Renovasi & Penguatan",
  service3_desc: "Perbaikan dan penguatan struktur bangunan eksisting untuk meningkatkan kapasitas beban dan umur bangunan.",
  service4_title: "Desain & Konsultasi",
  service4_desc: "Layanan desain teknik struktur baja menggunakan perangkat lunak CAD dan analisis beban profesional.",

  projects_section_label: "Portofolio",
  projects_title: "Proyek Yang Telah Kami Selesaikan",
  project_completed: "Selesai",
  project1_title: "Gudang Logistik Bekasi",
  project1_desc: "Konstruksi gudang logistik 10.000 m² dengan struktur baja ringan yang tahan gempa.",
  project1_highlight: "Kapasitas meningkat 35%",
  project2_title: "Pabrik Manufaktur Karawang",
  project2_desc: "Penguatan struktur lantai pabrik untuk penambahan beban mesin produksi seberat 120 ton.",
  project2_highlight: "Zero downtime operasional",
  project3_title: "Kanopi Komersial Jakarta",
  project3_desc: "Desain dan konstruksi kanopi parkir area komersial dengan desain modern dan tahan cuaca.",
  project3_highlight: "Umur pakai 25+ tahun",

  workflow_section_label: "Proses Kerja",
  workflow_title: "Bagaimana Kami Bekerja",
  workflow1_title: "Konsultasi & Survey",
  workflow1_desc: "Kunjungan lokasi dan analisis kebutuhan proyek secara detail.",
  workflow2_title: "Desain Teknik",
  workflow2_desc: "Pembuatan gambar desain dan perhitungan struktur dengan CAD.",
  workflow3_title: "Fabrikasi",
  workflow3_desc: "Pemotongan, pengelasan, dan finishing komponen di workshop.",
  workflow4_title: "Instalasi",
  workflow4_desc: "Pemasangan struktur di lokasi dengan tim profesional.",
  workflow5_title: "Quality Check",
  workflow5_desc: "Inspeksi akhir dan penyerahan proyek dengan garansi.",

  advantages_section_label: "Keunggulan",
  advantages_title: "Mengapa Memilih Kami",
  adv1_title: "Mesin Modern",
  adv1_desc: "Menggunakan peralatan fabrikasi CNC untuk presisi tertinggi.",
  adv2_title: "Desain CAD",
  adv2_desc: "Perencanaan struktur dengan software teknik profesional.",
  adv3_title: "Insinyur Berpengalaman",
  adv3_desc: "Tim dengan sertifikasi dan pengalaman lebih dari 10 tahun.",
  adv4_title: "Kontrol Kualitas Ketat",
  adv4_desc: "Setiap komponen melewati 3 tahap inspeksi sebelum dipasang.",

  testimonials_label: "Testimoni Klien",
  testimonials_title: "Apa Kata Klien Kami",
  testimonial1_text: "Proyek gudang kami selesai 2 minggu lebih cepat dari jadwal. Kualitas struktur sangat memuaskan dan tim sangat profesional.",
  testimonial1_name: "Budi Santoso",
  testimonial1_position: "Direktur Logistik Nusantara",
  testimonial2_text: "Penguatan struktur pabrik kami berjalan tanpa menghentikan produksi. Sangat profesional dan memahami kebutuhan industri.",
  testimonial2_name: "Siti Rahayu",
  testimonial2_position: "Manajer Pabrik Multi Manufaktur",
  testimonial3_text: "Desain kanopi yang dibuat sangat sesuai dengan konsep bangunan kami. Pengerjaan rapi dan on time. Sangat direkomendasikan.",
  testimonial3_name: "Andi Pratama",
  testimonial3_position: "Pemilik Gedung Komersial Jakarta",

  contact_section_label: "Hubungi Kami",
  contact_title: "Siap Membangun Proyek Anda?",
  contact_description: "Konsultasikan proyek konstruksi baja Anda dengan tim ahli kami. Kami akan memberikan penawaran terbaik dan solusi yang sesuai dengan kebutuhan Anda.",
  contact_phone_label: "Telepon",
  contact_address_label: "Alamat",
  contact_response_label: "Waktu Respon",
  contact_response_text: "Kami akan menghubungi Anda dalam 24 jam",
  contact_cta_whatsapp: "Hubungi via WhatsApp",
  contact_label_name: "Nama Lengkap",
  contact_label_email: "Email",
  contact_label_phone: "Nomor Telepon",
  contact_label_message: "Detail Proyek",
  contact_placeholder_message: "Jelaskan tentang proyek yang ingin Anda bangun...",
  contact_submit: "Kirim Permintaan Konsultasi",

  footer_nav: "Navigasi",
  footer_contact: "Kontak",
  footer_description: "Perusahaan konstruksi baja profesional yang menyediakan solusi fabrikasi dan pembangunan struktur untuk proyek industri dan komersial di seluruh Indonesia.",
  footer_copyright: "© 2026 Ksatria Baja Nusantara. Seluruh hak cipta dilindungi."
}
